[tool]
[tool.poetry]
name = "HerlockUserbot_Deployer"
version = "1.0"
description = "Automatic Deploy HerlockUserBot to Heroku"
authors = ["Herlock"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
